# Generated by Django 5.0.6 on 2024-06-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0002_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='receipt_photos'),
        ),
    ]
