# Generated by Django 5.0.6 on 2024-06-28 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0003_alter_receipt_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='receipt_photos/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='steps',
            field=models.TextField(verbose_name='Шаги преготовления'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='time',
            field=models.PositiveIntegerField(verbose_name='Время (мин)'),
        ),
    ]
