# Generated by Django 5.0.6 on 2024-06-28 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0004_remove_category_photo_alter_category_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.category'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='receipt_photos/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='steps',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='time',
            field=models.IntegerField(),
        ),
    ]
